export const INDUSTRIES = {
  "IT & Software": {
    keywords: [
      "javascript",
      "python",
      "react",
      "node",
      "java",
      "django",
      "vue",
      "angular",
      "typescript",
      "php",
      "postgresql",
      "mongodb",
      "docker",
      "aws",
      "api",
      "qa",
      "testing",
      "devops",
      "scrum",
    ],
    icon: "💻",
    color: "\x1b[36m", // Cyan
  },
  "Medicină & Sănătate": {
    keywords: [
      "medicină",
      "medic",
      "diagnostic",
      "pacienți",
      "clinică",
      "asistent medical",
      "terapie",
      "nursing",
      "chirurgie",
      "farmacologie",
      "ecografie",
      "stomatologie",
      "farmacist",
    ],
    icon: "⚕️",
    color: "\x1b[32m", // Green
  },
  Educație: {
    keywords: [
      "predare",
      "profesor",
      "elevi",
      "curriculum",
      "didactic",
      "evaluare",
      "bacalaureat",
      "universitar",
      "pedagogie",
      "educator",
      "training",
      "formator",
      "cursuri",
    ],
    icon: "🎓",
    color: "\x1b[33m", // Yellow
  },
  "Financiar & Contabilitate": {
    keywords: [
      "contabilitate",
      "sap",
      "ifrs",
      "audit",
      "financiar",
      "bugetare",
      "raportare",
      "excel",
      "gestiune",
      "fiscal",
      "bancar",
      "economist",
      "facturare",
    ],
    icon: "💰",
    color: "\x1b[93m", // Bright Yellow
  },
  Juridic: {
    keywords: [
      "drept",
      "avocat",
      "litigii",
      "consultanță juridică",
      "procedură",
      "civil",
      "penal",
      "comercial",
      "muncii",
      "jurist",
      "notar",
      "contracte",
    ],
    icon: "⚖️",
    color: "\x1b[35m", // Magenta
  },
  "Inginerie & Construcții": {
    keywords: [
      "inginerie",
      "autocad",
      "proiectare",
      "structuri",
      "civil",
      "rezistența",
      "poduri",
      "constructor",
      "lean",
      "producție",
      "șantier",
      "instalator",
      "electrician",
      "topograf",
    ],
    icon: "🏗️",
    color: "\x1b[34m", // Blue
  },
  "Resurse Umane": {
    keywords: [
      "hr",
      "resurse umane",
      "recrutare",
      "onboarding",
      "legislația muncii",
      "employer branding",
      "dezvoltare personală",
      "salarizare",
      "revisal",
      "training",
    ],
    icon: "👥",
    color: "\x1b[96m", // Bright Cyan
  },
  "Design & Creativitate": {
    keywords: [
      "design",
      "grafic",
      "adobe",
      "photoshop",
      "illustrator",
      "branding",
      "ui/ux",
      "creative",
      "portfolio",
      "vizual",
      "video",
      "editare",
      "artă",
    ],
    icon: "🎨",
    color: "\x1b[95m", // Bright Magenta
  },
  "Logistică & Transport": {
    keywords: [
      "logistică",
      "supply chain",
      "aprovizionare",
      "depozit",
      "stocuri",
      "transport",
      "distribuție",
      "warehouse",
      "șofer",
      "tir",
      "categoria c",
      "curier",
      "auto",
    ],
    icon: "🚚",
    color: "\x1b[91m", // Bright Red
  },
  "Vânzări & Marketing": {
    keywords: [
      "sales",
      "vânzări",
      "b2b",
      "crm",
      "marketing",
      "negociere",
      "prospectare",
      "social media",
      "seo",
      "copywriting",
      "reclame",
      "publicitate",
      "ads",
    ],
    icon: "📈",
    color: "\x1b[92m", // Bright Green
  },
  "Horeca & Turism": {
    keywords: [
      "bucătar",
      "ospătar",
      "recepție",
      "hotel",
      "restaurant",
      "barman",
      "turism",
      "catering",
      "evenimente",
      "haccp",
      "chef",
      "hotelier",
      "curățenie",
    ],
    icon: "🍽️",
    color: "\x1b[31m", // Red
  },
  "Auto & Mecanică": {
    keywords: [
      "mecanic",
      "service",
      "diagnoză",
      "tinichigiu",
      "vopsitor",
      "auto",
      "piese",
      "motor",
      "vulcanizare",
      "itp",
    ],
    icon: "🔧",
    color: "\x1b[90m", // Grey
  },
  Imobiliare: {
    keywords: [
      "imobiliare",
      "agent imobiliar",
      "tranzacții",
      "chirii",
      "vânzări case",
      "terenuri",
      "evaluator",
      "cadastru",
      "dezvoltator",
    ],
    icon: "🏠",
    color: "\x1b[33m", // Yellow
  },
  "Agricultură & Zootehnie": {
    keywords: [
      "agricultură",
      "agronom",
      "fermă",
      "tractorist",
      "zootehnie",
      "veterinar",
      "horticultură",
      "sere",
      "culturi",
    ],
    icon: "🌾",
    color: "\x1b[32m", // Green
  },
  "Administrativ & Secretariat": {
    keywords: [
      "secretară",
      "asistent manager",
      "office manager",
      "recepționer",
      "administrativ",
      "data entry",
      "arhivare",
      "birotică",
      "telefon",
    ],
    icon: "📁",
    color: "\x1b[37m", // White
  },
  "Client Service & Support": {
    keywords: [
      "call center",
      "suport clienți",
      "operator",
      "ticketing",
      "limba engleză",
      "franceză",
      "italiană",
      "spaniolă",
      "germană",
      "asistență",
    ],
    icon: "🎧",
    color: "\x1b[36m", // Cyan
  },
  "Beauty & Wellness": {
    keywords: [
      "coafor",
      "frizer",
      "cosmetică",
      "make-up",
      "masaj",
      "fitness",
      "antrenor",
      "salon",
      "manichiură",
      "estetică",
    ],
    icon: "💇",
    color: "\x1b[95m", // Bright Magenta
  },
  "Securitate & Pază": {
    keywords: [
      "pază",
      "agent securitate",
      "bodyguard",
      "supraveghere",
      "intervenție",
      "atestat pază",
      "monitorizare",
      "ordine publică",
    ],
    icon: "🛡️",
    color: "\x1b[34m", // Blue
  },
};

export const RESET_COLOR = "\x1b[0m";
